# Generated by Django 3.0.5 on 2024-05-11 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/TechnicianProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('skill', models.CharField(max_length=500, null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='request',
            old_name='vehicle_brand',
            new_name='service_brand',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='vehicle_model',
            new_name='service_model',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='vehicle_name',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='vehicle_no',
            new_name='service_no',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='request',
            name='mechanic',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Technician'),
        ),
        migrations.AddField(
            model_name='request',
            name='Technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Technician'),
        ),
    ]
