# Generated by Django 3.0.5 on 2024-05-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20240511_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='service_brand',
        ),
        migrations.RemoveField(
            model_name='request',
            name='service_model',
        ),
    ]
