# Generated by Django 5.0.4 on 2024-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20240511_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electricity', 'Electricity'), ('Painting', 'Painting'), ('Carpentry', 'Carpentry')], max_length=50),
        ),
    ]
